version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  
  kavitastats:
    image: kizaing/kavitastats:latest
    environment:
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: kavitaStats
      API_KEY: putapikeyhere
      ALLOWED_HOSTS: stats.kavitareader.com;kavitareader.com;localhost
    ports:
      - "5001:5001"
    depends_on:
      - mongo

volumes:
  mongodb_data_container:
